**Ensemble Technique** 





In [44]:
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
from sklearn import svm
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn 

In [2]:
df=pd.read_csv("Brain.csv")
df

meanHue    StdDev   meanvar  ...   entropy       energy  output
0    0.048050  0.213870  0.037532  ...  0.278050  206000000.0       1
1    0.084442  0.278050  0.062928  ...  0.417640  363000000.0       1
2    0.063950  0.244660  0.045596  ...  0.342930  275000000.0       1
3    0.086594  0.281240  0.061372  ...  0.425000  372000000.0       1
4    0.012604  0.111560  0.011385  ...  0.097598   54100000.0       1
..        ...       ...       ...  ...       ...          ...     ...
242  0.001160  0.034034  0.001151  ...  0.012981    4980000.0       0
243  0.000473  0.021744  0.000448  ...  0.005907    2030000.0       0
244  0.000061  0.007812  0.000061  ...  0.000943     262000.0       0
245  0.000168  0.012954  0.000166  ...  0.002347     721000.0       0
246  0.000565  0.023754  0.000553  ...  0.006906    2420000.0       0

[247 rows x 9 columns]

In [3]:
df.isnull().sum()

meanHue     0
StdDev      0
meanvar     0
areaf       0
skew        0
kurtosis    0
entropy     0
energy      0
output      0
dtype: int64

In [4]:
x=df.drop(['output'],axis=1)
x

meanHue    StdDev   meanvar  ...    kurtosis   entropy       energy
0    0.048050  0.213870  0.037532  ...     18.8620  0.278050  206000000.0
1    0.084442  0.278050  0.062928  ...      9.9345  0.417640  363000000.0
2    0.063950  0.244660  0.045596  ...     13.7050  0.342930  275000000.0
3    0.086594  0.281240  0.061372  ...      9.6428  0.425000  372000000.0
4    0.012604  0.111560  0.011385  ...     77.3530  0.097598   54100000.0
..        ...       ...       ...  ...         ...       ...          ...
242  0.001160  0.034034  0.001151  ...    860.3000  0.012981    4980000.0
243  0.000473  0.021744  0.000448  ...   2112.0000  0.005907    2030000.0
244  0.000061  0.007812  0.000061  ...  16382.0000  0.000943     262000.0
245  0.000168  0.012954  0.000166  ...   5955.7000  0.002347     721000.0
246  0.000565  0.023754  0.000553  ...   1769.2000  0.006906    2420000.0

[247 rows x 8 columns]

In [5]:
y=df['output']
y

0      1
1      1
2      1
3      1
4      1
      ..
242    0
243    0
244    0
245    0
246    0
Name: output, Length: 247, dtype: int64

In [6]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=40)

**Random Forest**

In [9]:
from sklearn.ensemble import RandomForestClassifier
RF=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, 
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=42,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
RF.fit(x_train,y_train)


RandomForestClassifier(n_estimators=42)

In [12]:
RF.score(x_test,y_test)

0.9797979797979798

In [13]:
pred=RF.predict(x_test)

In [14]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[39,  2],
       [ 0, 58]])

In [15]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.95      0.97        41
           1       0.97      1.00      0.98        58

    accuracy                           0.98        99
   macro avg       0.98      0.98      0.98        99
weighted avg       0.98      0.98      0.98        99



In [35]:
from sklearn.preprocessing import MinMaxScaler

**K Nearest Neighbour (KNN)**

In [16]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [17]:
knn.score(x_test,y_test)

0.9393939393939394

In [18]:
pred=knn.predict(x_test)

In [19]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[38,  3],
       [ 3, 55]])

In [20]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93        41
           1       0.95      0.95      0.95        58

    accuracy                           0.94        99
   macro avg       0.94      0.94      0.94        99
weighted avg       0.94      0.94      0.94        99



**Support Vector Mechine (SVM)**



In [21]:
from sklearn import svm
from sklearn.svm import SVC
SupportVectorClassModel=SVC()
SupportVectorClassModel.fit(x_train,y_train)

SVC()

In [22]:
SupportVectorClassModel.score(x_test,y_test)

0.9292929292929293

In [23]:
pred=SupportVectorClassModel.predict(x_test)

In [24]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[40,  1],
       [ 6, 52]])

In [25]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.87      0.98      0.92        41
           1       0.98      0.90      0.94        58

    accuracy                           0.93        99
   macro avg       0.93      0.94      0.93        99
weighted avg       0.93      0.93      0.93        99



**Decision Tree**

In [37]:
from sklearn.tree import DecisionTreeClassifier
dtclf=DecisionTreeClassifier()
dtclf.fit(x_train,y_train)

DecisionTreeClassifier()

In [38]:
dtclf.score(x_test,y_test)

0.9797979797979798

In [39]:
pred=dtclf.predict(x_test)

In [40]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[39,  2],
       [ 0, 58]])

In [41]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.95      0.97        41
           1       0.97      1.00      0.98        58

    accuracy                           0.98        99
   macro avg       0.98      0.98      0.98        99
weighted avg       0.98      0.98      0.98        99



In [42]:
dtclf=DecisionTreeClassifier()
rfc = RandomForestClassifier()
knn =  KNeighborsClassifier()
svc = SVC()

In [45]:
clf = [dtclf,rfc,knn,svc]
for algo in clf:
    score = cross_val_score( algo,x,y,cv = 5,scoring = 'accuracy')
    print("The accuracy score of {} is:".format(algo),score.mean()*100)

The accuracy score of DecisionTreeClassifier() is: 96.73469387755101
The accuracy score of RandomForestClassifier() is: 95.53469387755102
The accuracy score of KNeighborsClassifier() is: 93.10204081632654
The accuracy score of SVC() is: 88.67755102040817


**Stacked Model**

In [46]:
dtclf=DecisionTreeClassifier()
rfc = RandomForestClassifier()
knn =  KNeighborsClassifier()
svc = SVC()
clf = [('dtclf',dtclf),('rfc',rfc),('knn',knn),('svc',svc)]

In [47]:
lr = LogisticRegression()
stack_model = StackingClassifier( estimators = clf,final_estimator = lr)
stack_model.fit(x_train,y_train)


StackingClassifier(estimators=[('dtclf', DecisionTreeClassifier()),
                               ('rfc', RandomForestClassifier()),
                               ('knn', KNeighborsClassifier()),
                               ('svc', SVC())],
                   final_estimator=LogisticRegression())

In [48]:
stack_model.score(x_test,y_test)

0.9797979797979798

In [ ]:
pred=stack_model.predict(x_test)

In [49]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[39,  2],
       [ 0, 58]])

In [50]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.95      0.97        41
           1       0.97      1.00      0.98        58

    accuracy                           0.98        99
   macro avg       0.98      0.98      0.98        99
weighted avg       0.98      0.98      0.98        99

